name: Release

on:
  push:
    tags:
      - 'v*'
  create:
    branches:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package
        run: cd build && cpack

      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-package
          path: build/*.tar.gz

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.tar.gz  # Adjust to match what cpack generates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}