name: Build

on:
 push:
   branches: [master]
 pull_request:
   branches: [master]

jobs:
    build-linux:
        name: Linux
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v4
            - name: Build binary
              run: |
                cmake .
                make
            - name: Test
              run: ./LinearLib_Tests